AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple web site, load balanced, scalable, highly available"

Parameters:
  KeyName:
    Description: Name of SSH Keypair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: Must be an existing SSH keypair

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: webservers_vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: webservers_internet_gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
